[package]
name = "factory-kernel"
version.workspace = true
edition.workspace = true
license.workspace = true

[package.metadata.factory]
level = 0

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
chrono-tz.workspace = true
croner.workspace = true
serde.workspace = true
thiserror.workspace = true

[dev-dependencies]
serde_json.workspace = true
